### ISSUE TITLE
getDriver

### ISSUE THREAD

**Issue by char0n** [PixnBits/karma-selenium-webdriver-launcher#3]
Hi,

In your example configuration you have getDriver function, that configures the wedriver instance and I guess exposes it to tests.

What I don't get is how to call the getDriver function in tests. I have a test like this:

var driver = getDriver(); ????
driver.get('http://www.google.com');
driver.findElement(webdriver.By.name('q')).sendKeys('codescale');
driver.findElement(webdriver.By.name('btnG')).click();
driver.quit();

Am I missing something ?

Thanks a lot for the answer

**Comment by PixnBits** [comment]
Currently `getDriver` is just a configuration function called by the launcher.
This is the 2nd request for it in the test, though, so maybe exposing something similar should be implemented?

**Comment by PixnBits** [comment]
The first question/request was #1 
Have you checked that [Protractor](https://github.com/angular/protractor) is suitable for your needs? (see https://github.com/PixnBits/karma-selenium-webdriver-launcher/issues/1#issuecomment-76001591)

**Comment by char0n** [comment]
Thanks
